spring.application.name=reportes

server.port=${PORT:8080}

# Configuración de Conexión a Neon DB 
spring.datasource.url=${NEON_DB_URL}
spring.datasource.username=${NEON_DB_USER}
spring.datasource.password=${NEON_DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Estrategia JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}